# Generated by Django 6.1 on 2026-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
